## Introduction
-----
You (an electrical engineer) wish to determine the resistance of an electrical component by using Ohm's law. Using two different multimeters, you collect the following data:

| Multimeter A | Multimeter B |
|-------------|-------------|
| 1068         | 0        |
| 988         | 0        |
| 0         | 1002        |
| 0         | 996        |

where $\sigma_A$ = 20 ohms and $\sigma_B$ = 2 ohms

Your goal is to 
1. Consider what the best estimate of the resistance is, in ohms, for this component.

## Getting Started
----

First we will import the neccesary Python modules and load the current and voltage measurements into numpy arrays:

In [3]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt

## Estimating the Parameter
----
Let's try to estimate the resistance parameter using the weighted least squares formulation from Module 1, Lesson 1, Part 2 - "The Squared Error Criterion and the Method of Weighted Least Squares":

\begin{align}
\hat{x} = \left(\mathbf{H}^T\mathbf{R}^{-1}\mathbf{H}\right)^{-1}\mathbf{H}^T\mathbf{R}^{-1}\mathbf{y}
\end{align}

If we know that we're looking for the slope parameter $\hat{x}$, how do we define the jacobian matrix $\mathbf{H}$, variance matrix $\mathbf{R}$, and measurement vector $\mathbf{y}$?

In [22]:
# Define the H matrix, what does it contain?
# H is the conversion from measurement to parameter space, in this case all 1
H = np.mat([1, 1, 1, 1]).T

# R is the covariance of the measurements
sigma_a = 20
var_a = sigma_a**2
sigma_b = 2
var_b = sigma_b**2
R = np.mat([[var_a, 0, 0 ,0],
            [0, var_a, 0, 0],
            [0, 0, var_b, 0],
            [0, 0, 0, var_b]])

# y is the measurements from each reading
y = np.mat([1068, 988, 1002, 996]).T

# Now estimate the resistance parameter.
x_hat = np.linalg.inv(H.T*np.linalg.inv(R)*H)*H.T*np.linalg.inv(R)*y # calculate matrix
x_hat = np.asscalar(x_hat) # convert to scalar

print("The input matrices are:")
print("H:\n",H)
print("R:\n",R)
print("y:\n",y)
print()
print('The resistance parameter using weighted least squares is:')
print(x_hat)


The input matrices are:
H:
 [[1]
 [1]
 [1]
 [1]]
R:
 [[400   0   0   0]
 [  0 400   0   0]
 [  0   0   4   0]
 [  0   0   0   4]]
y:
 [[1068]
 [ 988]
 [1002]
 [ 996]]

The resistance parameter using weighted least squares is:
999.2871287128713


Value given in video: 999.3